ecommerce/common/urls.py
from django.urls import path
from .import views

urlpatterns = [
    
    path('',views.common_home),
]

ecommerce/delivery/urls.py
from django.urls import path
from .import views

app_name = 'delivery'

urlpatterns = [
    
    path('index',views.delivery_home, name = 'deliveryhome'),
]

ecommerce/ecommerce/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('common.urls')),
    path('delivery/',include('delivery.urls'))
]

ecommerce/common/models.py
from django.db import models

# Create your models here.

ecommerce/delivery/models.py
from django.db import models

# Create your models here.

ecommerce/common/views.py
from django.shortcuts import render

# Create your views here.
def common_home(request):
    return render(request,'commontemp/index.html')

ecommerce/delivery/views.py
from django.shortcuts import render

# Create your views here.
def delivery_home(request):
    return render(request,'deliverytemp/index.html')

ecommerce/common/templates/commontemp/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1><a href="{% url 'delivery:deliveryhome' %}">goto</a></h1>
    <img src="{% static 'images/sumo-convert.png' %}" />
</body>
</html>

ecommerce/delivery/templates/deliverytemp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Delivery Home Page from delivery app</h1>
</body>
</html>